### ISSUE TITLE
[Bug] Dark theme not working

### ISSUE THREAD

**Issue by dspacejs** [Taiko2k/Avvie#13]
I have the dark theme set on my machine. It works with all apps but this one:

![Dark theme not working](https://user-images.githubusercontent.com/9282837/94352339-d1d48580-00a2-11eb-8b78-44e6a1937c5e.pn g)

I checked the settings and there doesn't seem to be a way to switch to a dark theme. The screenshot in the README is dark, so I'm not sure why this doesn't work.

## Environment

* Ubuntu 20.04.1 LTS
* Gnome 36.36.3
* Regolith 2.63-1focal1

**Comment by Taiko2k** [comment]
Its actually intended to be dark theme only. I don't think there's any issue with Avvie.

I believe this is an issue related to Flatpak when you use a custom theme that isn't also packaged for Flatpak, it defaults to Adwaita light. Could be considered a bug, though you can also solve the issue by getting your theme packaged for Flatpak.

**Comment by dspacejs** [comment]
@Taiko2k just looked into that and struggling to do so.

I installed `org.gtk.Gtk3theme.Adwaita-dark`. But I don't know how to configure flatpak to use it. I've tried looking online with no luck. Do you have any ideas?

**Comment by Taiko2k** [comment]
If you have your custom system theme applied, then running `flatpak update` should automatically install it if available. Though Adwaita-dark should be built in by default. Are you running a custom theme, or the default Adwaita?

**Comment by dspacejs** [comment]
@Taiko2k hmm, `flatpak update` didn't work.

I'm not using a custom theme. I'm using Ubuntu's default dark theme in the system settings. Although I'm also using Regolith, which is basically a custom i3 setup for Ubuntu (maybe this has some theming config that's messing with it)?

**Comment by Taiko2k** [comment]
Just did a test with latest vanilla Ubuntu 20.04 and seems to be working as expected.

![Screenshot from 2020-09-27 18-16-40-cropped](https://user-images.githubusercontent.com/17271572/94356703-b8a4f680-00ed-11eb-9548-d19c83d945df.jpg)

So likely something to do with your configuration.

**Comment by dspacejs** [comment]
@Taiko2k hmm strange. Maybe a reboot or something will fix it. I'll figure it out eventually

**Comment by SuperZoops** [comment]
Try the permissions command, that fixed themeing issues for me.

**Comment by dspacejs** [comment]
@SuperZoops what's the name of the permission you used with `permission-set`?

**Comment by Exalm** [comment]
> I believe this is an issue related to Flatpak when you use a custom theme that isn't also packaged for Flatpak, it defaults to Adwaita light. Could be considered a bug, though you can also solve the issue by getting your theme packaged for Flatpak (on Flathub).

It's GTK doing it. It shouldn't be an issue with libadwaita or libhandy.

**Comment by Taiko2k** [comment]
This probably isn't reverent any more with the switch to Adwaita I assume. Ill close this.
