### ISSUE TITLE
Version tags and releases

### ISSUE THREAD

**Issue by dusansimic** [Taiko2k/Avvie#16]
Currently there is only one version tag and it's for `1.0-beta1`. Because of this distribution package maintainers need to track down on which commit there was a version change and use that commit for building a package. It would be much easier for package maintainers to update packages if there were git tags for each version marking the commit that should be used.

Another useful thing would be to create releases for those tags as you already did so a tar.gz archive can be used for fetching source code instead of the entire repo.

Thanks for a great app 😁!

**Comment by Taiko2k** [comment]
Alright, I will do that from now on and have made one now for the current version.
