### ISSUE TITLE
libGL error: MESA-LOADER: failed to retrieve device information

### ISSUE THREAD

**Issue by jakubiszon26** [Taiko2k/Avvie#19]
Avvie doesn't start.
os: fedora 36
integrated intel gpu

couldn't open /dev/dri/card1 (No such file or dirctory)

![obraz](https://user-images.githubusercontent.com/61655602/162299999-013c4ac6-7c5a-4641-8131-e4e2a1c4761a.png)

**Comment by Taiko2k** [comment]
I've pushed a flatpak update, can you tell if it's working now?
