### ISSUE TITLE
About dialog isn’t tied to the main window

### ISSUE THREAD

**Issue by musiclover382** [Taiko2k/Avvie#26]
I noticed the about dialog is a completely independent window, while on gnome apps the dialog and the main windows are tied each other (the same way the preferences dialog currently is in Avvie). I think it would be great if Avvie behaved the same way

**Comment by Taiko2k** [comment]
I noticed this, but I dont know how to fix this issue.

**Comment by Taiko2k** [comment]
Ok I've managed to fix this up now
