### ISSUE TITLE
Build and install instructions

### ISSUE THREAD

**Issue by Taiko2k** [Taiko2k/Avvie#27]
We should add instructions on how to build, run and install the project. Either to README.md file, or a github wiki page.

**Comment by musiclover382** [comment]
You can build the program either using gnome builder, flatpak-builder or native build directly with meson. The latter can be done with the following commands:
```
meson build --prefix=/usr/local
ninja -C build install
```
I’m gonna submit a PR later to add the complete instructions in the readme if you want.

**Comment by Taiko2k** [comment]
Is there a way to do it without installing to system? Like if I'm just testing, I don't wanna have to enter my password.

**Comment by musiclover382** [comment]
You can use flatpak-builder:
```
flatpak-builder --user --install builddir com.github.taiko2k.avvie.yml
flatpak run com.github.taiko2k.avvie
```
If you are on Arch Linux, you can use the PKGBUILD from the AUR commenting out the source and b2sums lines, put the source in src/avvie and then build & install the package with `makepkg -rsif`

With gnome builder, you can simply select “clone repository”, then click the play button in the topbar and the IDE will automatically build and run the program

**Comment by Taiko2k** [comment]
I had the Flatpak working. And oh neat you got a working PKGBUILD. Will need to remind the maintainer of the non-git version to update theirs on release of Avvie v2.1.

I committed a change that allowing running of the main.py straight from source. Makes testing easier.

As for native building, I assume we can just do:

```
$ meson builddir && cd builddir
$ meson compile
$ meson install
```

same thing right?

**Comment by eli-schwartz** [comment]
An alternative to running without installing would be to generate two versions of the entrypoint script. One is configured for installation, and installed... the other uses paths pointing into the build tree to bind the translations to that location (`<builddir>/po/`).

This would allow e.g. testing translation updates without installing. Current versions of Meson ensure that the built translations are usable (have the right directory structure) in the build tree.
