### ISSUE TITLE
Switch to GTK for notifications rather than libnotify

### ISSUE THREAD

**Issue by ZanderBrown** [Taiko2k/Avvie#3]
You can use GtkApplication to handle opening files and notifications

This means you don't need libnotify (which is kinda deprecated now) and don't have to do manual `argv` parsing

Neat little app you've got here!

**Comment by musiclover382** [comment]
Is this fixed?

**Comment by Taiko2k** [comment]
Yes this is fixed in master. But not in a current release yet.
