### ISSUE TITLE
New Icon?

### ISSUE THREAD

**Issue by bertob** [Taiko2k/Avvie#5]
Would you be interested in a new icon following the [GNOME icon guidelines](https://developer.gnome.org/hig/stable/icon-design.html.en)? If so, I'd be happy to help with that.

**Comment by Taiko2k** [comment]
If you can, that would be appreciated!

**Comment by bertob** [comment]
How about something like this? A lot of the image/media-related apps have these gradient surfaces, so I wanted to try that here too.

![image](https://user-images.githubusercontent.com/1908896/64862642-56d53400-d633-11e9-91c5-50dd13c9bc9d.png)

(the symbolic is just a placeholder for now)

**Comment by Taiko2k** [comment]
Wow that's pretty cool! I have no objections!

Might be interesting to see different gradient colours. Hmm, it loses the angular feel, maybe rotate to a diamond?... Ah, but then it would lose its symbolic meaning. :thinking: 

Certainly acceptable as is there!

**Comment by bertob** [comment]
I think the shape is growing on me, but I'm still experimenting with some different gradients. I'd like to keep the vibrant colors of the current icon and give this app a more distinct personality.

Is this too over the top?

![image](https://user-images.githubusercontent.com/1908896/65271179-eccdfa80-db1c-11e9-896e-e2be143425ac.png)

**Comment by Taiko2k** [comment]
I think the cyan here doesn't have good visual harmony. The first example worked well.

**Comment by bertob** [comment]
Fair enough :)

What if we go back to white for the corners but keep the peach gradient?

![image](https://user-images.githubusercontent.com/1908896/65321408-665cfb80-dba4-11e9-9c44-18e0dedac142.png)

**Comment by Taiko2k** [comment]
Hard to choose actually. Haha. White corners defiantly looks better. Though, I get the feeling the first you did with the purple/violet gradient is *better* as an icon, nicer to look at visually. 
___

BTW, when you're ready, you can make a PR if you like (replacing `com.github.taiko2k.avvie.svg`, adding `com.github.taiko2k.avvie-symbolic.svg`) so you get credited as a contributor. Also tell me what name you'd like to be credited by in the app, or you could edit it yourself (Un-comment line `611` of `main.py` and replace the text there with your name)

**Comment by bertob** [comment]
Ok, let's go with the first one then.

I took a quick look at replacing the icon in the app, but I couldn't really figure it out. What I can do is make a PR that simply replaces the icon files, and then you can make it actually use the new icon after that.

**Comment by Taiko2k** [comment]
Cool!

> simply replaces the icon files, and then you can make it actually use the new icon after that.

Actually that's all you need to do, the rest is automatic.

**Comment by Taiko2k** [comment]
Thanks for the contribution! Ill push it in an update sometime soon.
