### ISSUE TITLE
Retain metadata for cropped image

### ISSUE THREAD

**Issue by muelli** [Taiko2k/Avvie#7]
I would like the app to be able to retain metadata, in particular all the EXIF data.

**Comment by Taiko2k** [comment]
Okay, I've added in an option named "Discard EXIF" which defaults to OFF. Also added an indicator to show if the exported image will have EXIF data:

![Screenshot from 2019-09-29 13-49-35](https://user-images.githubusercontent.com/17271572/65824145-72da0600-e2c0-11e9-82cf-75501efe68a2.png)

Will be available in the next release.
