### ISSUE TITLE
[Feature Request] Changing the size of preview

### ISSUE THREAD

**Issue by contactobscurantist** [Taiko2k/Avvie#8]
First, thank you for this program!

It would be really great to be able to change the size of preview.
For example by dragging a corner of the preview, or/and using custom input.
Also, being able to see multiple previews of different sizes side by size (i.e. 64x64, 128x128, 360x360) can help creating icons or avatars for sites that re-use one image in UI elements of different sizes.

**Comment by Taiko2k** [comment]
Okay. I've now added settings to the main menu for these. Its just custom input, hopefully not too awkward but should make sense I think.

![Screenshot from 2019-10-14 17-03-24-cropped](https://user-images.githubusercontent.com/17271572/66728989-add55f80-eea4-11e9-97ba-1f6dbe0c597e.jpg)

Ive also made it so you can remove a preview by middle mouse clicking. And the active previews will be remembered on restart.

**Comment by Taiko2k** [comment]
Okay, this feature is now available in the latest update.

**Comment by contactobscurantist** [comment]
Endless respect for you! It looks even better than I had imagined
