### ISSUE TITLE
Saving to downloads directory is not intuitive 

### ISSUE THREAD

**Issue by TomaszGasior** [Taiko2k/Avvie#9]
When I edit file I just want to save it, I mean replace. There is unwritten pattern in software which I see around (Paint, GIMP, Word, LibreOffice, gedit, Notepad, etc.)—you can save (replace current file) or save as (create new file and do not replace original one). Your app recommends saving copy of the file to downloads which IMHO is not intuitive. Also, there is no way to just save file (replace original one).  It seems to me gedit uses better approach — there is save (replace current file) button in the headerbar and save as command in application  menu. Please consider implementing something like in gedit — it's much more intuitive I think.

Thank you for good app for which I was looking for!

**Comment by Taiko2k** [comment]
Indeed the *save to downloads* button isn't something you normally see. However as for myself I use it all the time, I find it much faster than opening the save dialogue.

I think generally you wouldn't want to overwrite the original file. In fact this *is* how GIMP works. In GIMP pressing save button does not overwrite any original image you are editing. I think that is the preferred behavior of an image editing app.

So a) I think having a dedicated overwrite button should be avoided, b) I think the "quick save to downloads" button is too useful to remove.

You can still save using the "Export As" button within the menu. Though I'm open to hearing other ideas on moving things around. Maybe that export button should be in the header bar also...?

**Comment by TomaszGasior** [comment]
> I think generally you wouldn't want to overwrite the original file. In fact this is how GIMP works. In GIMP pressing save button does not overwrite any original image you are editing. I think that is the preferred behavior of an image editing app.

The main difference between Avvie and GIMP is that GIMP has its own specific image format which allows to store layers, metadata etc., so GIMP's user needs to distinguish save operation (save as native GIMP format) and export operation (save to target, commonly used format). From the other hand, your app is just simple image editor and my default intuition is to use this kind of software to edit (I mean: overwrite) my image file **directly** with optional, alternative "save as" option available. 

> Indeed the save to downloads button isn't something you normally see. However as for myself I use it all the time, I find it much faster than opening the save dialogue.

The main problem with "save to downloads" idea is that it's counterintuitive and incompatible with meaning of XDG downloads directory. Downloads directory is designed for files downloaded from the internet (in most cases: by web browser, sometimes by apps like virtual machines managers, like GNOME Boxes). When you edit your image, you don't download any data from web, you just edit your file. "Downloads" directory is not intended to be target of edited file. "Pictures" might be better semantically. But still my first default intuition is to just overwrite current file.

**Comment by Taiko2k** [comment]
Yeah it was really because of my own workflow that I chose Downloads. Pictures would make more sense as a default.

Hmm, here's an idea: In the main popover menu, have the following options:
 - Quick export to pictures
 - Quick export to downloads
 - Export as... (opens save dialogue)
 - Overwrite existing file

And the quick button in the header bar change automatically to whatever the users last selection was of those items. (So it kind of adapts to the users workflow) 

I still think "save" terminology should be avoided in an image app.

**Comment by Taiko2k** [comment]
Sorry for being late on this. I agree with this issue in general. The export to *downloads* folder is a little unexpected. Ive released an update with the following change:

The quick export button now defaults to the **Pictures** folder, and there is now a setting to switch the output between Pictures, Downloads or to **overwrite** the source file. This setting will persist on restarts.
